### ISSUE TITLE
为文章加入音乐播放器

### ISSUE THREAD

**Issue by KeJunMao** [KeJunMao/jekyll-theme-mdui#10]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.space/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [ ] bug report 
- [x] feature request
- [ ] support request

---

这是一个可能开发的萌功能。

这个功能允许在文章 yaml 头中指定音乐链接或163音乐id，并在生成的文章页中加入此歌曲。

使用该功能必须禁用全局播放器。

还在用这个破主题的 dalao 有没有什么见解。蟹蟹

**Comment by LamGC** [comment]
可以把全局播放器的音乐设置作为缺省值吧，文章页没有指定就用全局，有就禁用-w-

**Comment by KeJunMao** [comment]
@LamGC 没办法呢，因为ajax，全局播放器不会被刷新。感觉必须禁用全局播放器 ):

**Comment by KeJunMao** [comment]
弃坑。
