### ISSUE TITLE
代码没有高亮怎么办

### ISSUE THREAD

**Issue by DolaBMOon** [KeJunMao/jekyll-theme-mdui#13]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.space/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [ ] bug report 
- [ ] feature request
- [x] support request

**Comment by KeJunMao** [comment]
如何重现你的问题？

**Comment by DolaBMOon** [comment]
emm...
您可以看一下我fork过去的然后随机点一篇比如
   https://dolabmoon.github.io/technology/2017/11/04/ExDSU.html
