### ISSUE TITLE
多个Category同时存在时无法正常断开

### ISSUE THREAD

**Issue by daizhirui** [KeJunMao/jekyll-theme-mdui#15]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.space/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [x] bug report 
- [ ] feature request
- [ ] support request

如图所示，Technology和Wiki没有分开。点击该处会跳转到TechnologyWiki的页面，而不是Technology或Wiki中的一个。
![2018-01-29 7 09 19](https://user-images.githubusercontent.com/26495795/35508482-7ab3e400-052b-11e8-8ce6-7d1e245da55c.png)

**Comment by KeJunMao** [comment]
主题仅支持同一文章属于某一分类，使用 tag 吧。抱歉了

**Comment by daizhirui** [comment]
噢，好的，谢谢！我试了好几个主题，你这个是开箱最快的。很多好看的主题存在依赖问题无法解决。

On 2018年1月30日 +0800 PM1:30, KeJun <notifications@github.com>, wrote:

主题仅支持同一文章属于某一分类，使用 tag 吧。抱歉了

**Comment by KeJunMao** [comment]
谢谢，这个破主题也停更了，坐等V2吧~
