### ISSUE TITLE
Cannot change language

### ISSUE THREAD

**Issue by j-plo** [KeJunMao/jekyll-theme-mdui#16]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.space/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [ ] bug report 
- [ ] feature request
- [x] support request
---
If I change the `lang` setting in `_data/site.yml` it is still in chinese. How do i fix that?

**Comment by KeJunMao** [comment]
Make sure that there is a corresponding `lang` in `_data/lang.yml`.

Currently, this theme only support `zh-CN` and `en-US`.

But,You can manually create your `lang` according to the template(_data/lang.yml).

Forgive my English.

**Comment by j-plo** [comment]
#### WELL
Its still not working. I set up the `lang` setting to `pl-PL` and added a corresponding lang in `lang.yml` and now the site is in English

**Comment by KeJunMao** [comment]
Fix it.If you like, you can create a PR to submit your `lang.yml`
