### ISSUE TITLE
feature request: 添加文章多分类（category）支持

### ISSUE THREAD

**Issue by Rasphino** [KeJunMao/jekyll-theme-mdui#25]
**I certify that I have first consulted** (check all with "x")

- [ ] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.space/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [ ] bug report 
- [x] feature request
- [ ] support request

----
**背景**：
有时候一篇博文会有不止一个分类的情况：比如我使用living和tech两个大分类，但是tech类下还能细分出例如linux、java等子分类。个人感觉把子分类直接当作tag还是太“大”了一点，所以希望能支持一篇博文多个category。

----
其实我自己研究了一下，已经差不多修改好了，具体修改方法如下：
[我的解决办法](https://github.com/Rasphino/rasphino.github.io/commit/fc030caab75aa757309973de24deaa4f343abcd2)

修改之后的效果如下：
![2018-11-15_15-34](https://user-images.githubusercontent.com/12711106/48537245-f29af400-e8eb-11e8-8314-6e52dd24fa6c.png)

**Comment by KeJunMao** [comment]
谢谢，不错的想法，只是这个主题最初并不想支持。如果你有能力维护这个功能请开pr。再次感谢。
