### ISSUE TITLE
关于icon值的请教

### ISSUE THREAD

**Issue by oOtroyOo** [KeJunMao/jekyll-theme-mdui#34]
请教一下 类似于
`icon: "&#xe53b;"` ，` icon: "&#xe150;"`
这样的图标数值是在哪可以了解。

[Material icons](https://material.io/icons/)上面只找到了预设的名字，例如 `home`，`label`

**Comment by KeJunMao** [comment]
`&#xe53b;` 是CSS 框架 MDUI 为了兼容低版本浏览器,(Material icons已经可以直接使用 `home`)
不考虑兼容问题你可以直接使用 `home` ，或在[这里](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints)查看对应的 codepoints

**Comment by oOtroyOo** [comment]
谢谢，我去fork一个。

刚才我在查阅 MDUI的时候发现了这个文档
[Material 图标](https://www.mdui.org/docs/material_icon)
里面就有这种值

**Comment by KeJunMao** [comment]
蟹蟹支持～
