### ISSUE TITLE
无法解析http://mdui.kejun.space

### ISSUE THREAD

**Issue by moeKiwiSAMA** [KeJunMao/jekyll-theme-mdui#35]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.space/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [x] bug report 
- [ ] feature request
- [ ] support request

就..无法解析

**Comment by KeJunMao** [comment]
使用 kejun.me
