### ISSUE TITLE
不能按下任何按钮

### ISSUE THREAD

**Issue by Sunbertrs** [KeJunMao/jekyll-theme-mdui#36]
**I certify that I have first consulted** (check all with "x")

- [ ] [Jekyll documentation ](https://jekyllrb.com/)
- [ ] [jekyll-theme-mdui documentation ](http://mdui.kejun.space/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [x] bug report 
- [ ] feature request
- [x] support request

---

不能在*网站.com/jekyll-mdui*后按下任何有a的内容。  
比如 **文章背景**、**文章标题**、**侧边栏的所有按钮**、**作者Living**、**网站底部的Power by和Theme by**

**Comment by KeJunMao** [comment]
emmmm 还好嘛？
