### ISSUE TITLE
添加404页面

### ISSUE THREAD

**Issue by Sunbertrs** [KeJunMao/jekyll-theme-mdui#38]
**I certify that I have first consulted** (check all with "x")

- [ ] [Jekyll documentation ](https://jekyllrb.com/)
- [ ] [jekyll-theme-mdui documentation ](http://mdui.kejun.space/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [x] bug report 
- [x] feature request
- [x] support request

---  

这个模板本身没有404错误页面还有403错误页面。所以我认为弄这个很有必要。  
现在这些页面已经在我的网站中开始制作。如果你们想要帮忙的，你们可以等我发上PR然后你们可以继续修改。  
希望 @KejunMao 可以知悉。  
而如果觉得我的404和403页面做的不好，可以在这个issue里提出其他的建议。  
---
点击这两个链接来查看404和403页面  
https://sunbossrs.github.io/404.html  
https://sunbossrs.github.io/403.html

**Comment by SunbossRS** [comment]
它只可以直接写在404或403页面里(liquid语法也能使用)，但不能引用再引用

**Comment by Sunbertrs** [comment]
现在我已经放出了PR是在#39号。
这是我第一次提交批量文件PR。

**Comment by KeJunMao** [comment]
仔细看了一下，觉得 `404` 还是不要用 spa 的方式了吧？因为内容本身是不应该出现导向到不存在的页面的。

**Comment by Sunbertrs** [comment]
哦

**Comment by KeJunMao** [comment]
很感谢提出的pr，我会先尝试合并到主分支
