### ISSUE TITLE
无法转到cname

### ISSUE THREAD

**Issue by Sunbertrs** [KeJunMao/jekyll-theme-mdui#42]
**I certify that I have first consulted** (check all with "x")

- [ ] [Jekyll documentation ](https://jekyllrb.com/)
- [ ] [jekyll-theme-mdui documentation ](http://mdui.kejun.me/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [x] support request

---

我最近注册了一个域名，叫做[js.org](https://sunbossrs.js.org/)，但是当我访问[github.io](https://sunbossrs.github.io/)时，能访问，不过看到的是**最后一次在添加CNAME之前更新的内容**。而不会跳转到[js.org](https://sunbossrs.js.org/)   
初步判断是sw.js的问题

**Comment by Rasphino** [comment]
这应该是本地缓存造成的问题，可以尝试在github.io页面刷新，或者直接清除本地缓存

如果有更好的sw.js的实现，非常欢迎pr

**Comment by Sunbertrs** [comment]
额。。清了缓存，进去了还是老样子，只不过加载有点久

**Comment by DavyVan** [comment]
我也遇到过缓存问题，我干脆直接禁用了PWA，而且还需要在chrome浏览器中取消注册Service Worker才能真正清除缓存

**Comment by Sunbertrs** [comment]
谢谢。问题终于解决了，要把`/_includes/component/sw.html`的`register`字符改成`unregister`
