### ISSUE TITLE
使用vssue时会发送两个评论

### ISSUE THREAD

**Issue by Sunbertrs** [KeJunMao/jekyll-theme-mdui#43]
**I certify that I have first consulted** (check all with "x")

- [ ] [Jekyll documentation ](https://jekyllrb.com/)
- [ ] [jekyll-theme-mdui documentation ](http://mdui.kejun.me/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [x] bug report
- [x] feature request
- [x] support request

---

已弃坑gitalk并使用vssue，但是在发送评论时会发送两个。  
  
相关链接:  
[vssue上提出的问题](https://github.com/meteorlxy/vssue/issues/49)  
[在我的网站中的评论](https://github.com/SunbossRS/SunTalk_Save/issues/60)  
[我的网站评论实验文章](https://sunbossrs.js.org/living/2019/05/21/StartMduiTheme.html)

**Comment by w311ang** [comment]
干嘛关闭啊，我用Valine也有这样的问题。

**Comment by Sunbertrs** [comment]
我在怀疑是不是sw.js的问题
