### ISSUE TITLE
lack  `content/403x.html`

### ISSUE THREAD

**Issue by xizeyoupan** [KeJunMao/jekyll-theme-mdui#46]
**I certify that I have first consulted** (check all with "x")

* [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.me/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

lack  `content/403x.html`

**Comment by xizeyoupan** [comment]
It's in `_includes`

**Comment by xizeyoupan** [comment]
![200118154837](https://user-images.githubusercontent.com/44920131/72660519-20a52800-3a0a-11ea-94ca-7eb39c4bbef2.png)

Tried 404(403) Page but doesn't work Σ( ° △ °|||)︴

**Comment by KeJunMao** [comment]
谢谢
