### ISSUE TITLE
无法显示中文分类下的文章

### ISSUE THREAD

**Issue by w311ang** [KeJunMao/jekyll-theme-mdui#49]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.me/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

假如现在有个分类名是`闲话`的文章，按照步骤在根目录`category`文件夹创建一个`闲话.html`并填入相关内容后，访问其页面无法显示这个文章。

**Comment by KeJunMao** [comment]
请参考[常见问题](http://mdui.kejun.me/#/zh-cn/common-problem?id=%e6%97%a0%e6%b3%95%e4%bd%bf%e7%94%a8%e4%b8%ad%e6%96%87%e5%88%86%e7%b1%bb%ef%bc%9f)
