### ISSUE TITLE
请问如何增加支持高亮的语言？

### ISSUE THREAD

**Issue by moi-mo** [KeJunMao/jekyll-theme-mdui#51]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.me/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [ ] feature request
- [x] support request

请问如何增加prism支持语言……是直接在```/data/site.yml```里面新加上吗？这样的话并没有渲染……
<br>
[我的site.yml](https://github.com/moi-mo/moi-mo.github.io/blob/master/_data/site.yml)
[包含并没有被渲染的c++代码的文章](https://moi-mo.github.io/code/2020/03/09/type-changing-problem.html)
- 确认上面那篇文章中标注了语言为c++
- 但是在site.yml中自带的bash就可以正常渲染，且在site.yml中也可以直接通过改字符串的方式切换prism的主题

**Comment by KeJunMao** [comment]
你好，[原理](https://github.com/KeJunMao/jekyll-theme-mdui/blob/0b4b8aa60bebed773c2f58c6276502387e4d717d/_includes/content/component/highlight.html#L10-L12)就是根据 components 的值引入对应 js.

按照你想要的写了个例子：
```yaml
prism:
  themes: prism-solarizedlight
  components:
    - bash
    - python
    - c
    - cpp
```

推荐你在[这里](https://www.bootcdn.cn/prism/)，浏览器搜索，然后输入 `components/prism-[语言]` 来检查是否有支持！

🥳

**Comment by moi-mo** [comment]
那应该是把cpp写成c++了吧…x
谢谢！
