### ISSUE TITLE
TAG Page's bug

### ISSUE THREAD

**Issue by moi-mo** [KeJunMao/jekyll-theme-mdui#53]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.me/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

tag页面无法通过点击tag名展开文章列表了，试了一下[我的博客](https://rain.moimo.me)和示例博客的tag页面都出现了这个问题，可能是引用的库出了问题？

**Comment by KeJunMao** [comment]
无法复现
![image](https://user-images.githubusercontent.com/18414281/81541234-6153f300-93a5-11ea-9959-6c36d3f51a93.png)

**Comment by moi-mo** [comment]
那可能是我这边浏览器的问题吧……




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"KeJun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 下午4:35
收件人:&nbsp;"KeJunMao/jekyll-theme-mdui"<jekyll-theme-mdui@noreply.github.com&gt;;
抄送:&nbsp;"moi.rpy"<3066628847@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KeJunMao/jekyll-theme-mdui] TAG Page's bug (#53)





 
无法复现
