### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by zjs1925879492** [KeJunMao/jekyll-theme-mdui#55]
不同页面下导航栏显示不一样

**Comment by KeJunMao** [comment]
来个🌰，截图什么的

**Comment by zjs1925879492** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KeJun"<notifications@github.com&gt;; 
发送时间: 2020年8月13日(星期四) 下午2:03
收件人: "KeJunMao/jekyll-theme-mdui"<jekyll-theme-mdui@noreply.github.com&gt;; 
抄送: "&amp;#x202A;  &amp;#x206E;&amp;#x200E;"<1925879492@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [KeJunMao/jekyll-theme-mdui] Menu bug (#55)





 
来个，截图什么的

**Comment by zjs1925879492** [comment]
https://wx2.sbimg.cn/2020/08/13/3MhI4.png

https://wx2.sbimg.cn/2020/08/13/3MLzA.png

https://i.loli.net/2020/08/13/YRUTGqeLHw8IbMX.png

**我没有做任何改动，我只是为第三张图片更换了图床，（这些图片在github上都显示不出来）**

**Comment by KeJunMao** [comment]
开发主题时在控制台中禁用 sw

**Comment by zjs1925879492** [comment]
问题得到解决，谢谢
