### ISSUE TITLE
链接自动识别变蓝

### ISSUE THREAD

**Issue by w311ang** [KeJunMao/jekyll-theme-mdui#58]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.me/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [x] feature request
- [ ] support request

![Screenshot_20210208-172655](https://user-images.githubusercontent.com/30381083/107200582-dcc8fa80-6a32-11eb-9412-ee2b44f1f5d4.jpg)
希望这些链接可以自己变蓝可点击，不需要一个个`[]()`

**Comment by KeJunMao** [comment]
jekyll 支持 [automatic-links](https://kramdown.gettalong.org/syntax.html#automatic-links)，只有用 `<>` 把链接包起来就行。例子：

```md
Github: <https://github.com>
```
> source

---

Github: <https://github.com>
> result
