### ISSUE TITLE
Vercel环境下，使用本主题时报错

### ISSUE THREAD

**Issue by GrassBlock1** [KeJunMao/jekyll-theme-mdui#63]
**I certify that I have first consulted** (check all with "x")

- [x] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.me/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

----
如题 当我尝试使用[Vercel 官方模板部署的Jekyll](https://vercel.com/new/templates) 通过官方文档提示的办法（即修改Gemfile的方式）安装并启用本主题，再次部署时报错：

```
Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: comment/.html Valid syntax: {% include file.ext param='value' param2='value' %} in /vercel/path0/vendor/bundle/ruby/2.7.0/gems/jekyll-theme-mdui-0.5.4/_layouts/post.html
  	                    ------------------------------------------------
  	      Jekyll 4.2.0   Please append `--trace` to the `build` command 
  	                     for any additional information or backtrace. 
  	                    ------------------------------------------------
```

使用 ` jekyll build --trace` 跟踪的日志：
https://pastebin.com/wW937QXq

我的猜想是主题的gem包中 上述的模板文件出现了问题，导致了上述错误。

（~~如果主题开发者还在的话，希望修复一下 w~~ ）

**Comment by KeJunMao** [comment]
你好，我在本地使用 jekyll 4.2 尝试复现问题，但是并没有复现，一切正常。

如果你有时间可以试试编辑 `_includes/comment/comment.html` 文件，我猜测问题出在这
https://github.com/KeJunMao/jekyll-theme-mdui/blob/2bc7797afa915c4f6cdcd675366169d715b20006/_includes/comment/comment.html#L5

https://github.com/KeJunMao/jekyll-theme-mdui/blob/2bc7797afa915c4f6cdcd675366169d715b20006/_includes/comment/comment.html#L8

这里有类似的情况
- https://talk.jekyllrb.com/t/invalid-syntax-for-include-tag-using-a-variable/574
- https://github.com/jekyll/jekyll/issues/4739
- https://github.com/jekyll/jekyll/issues/6159

**Comment by GrassBlock1** [comment]
@KeJunMao 啊…Vercel 貌似不支持直接编辑主题源码…
（目录对用户不可见）

**Comment by GrassBlock1** [comment]
@KeJunMao （挖坟）本地测试了一下 还是有这个问题 （本地的环境是 ruby 3.1.2 及其配套gem,使用rvm安装）
而当我找到主题文件夹试图修改时，发现与上述内容完全不同（如图）

![图片](https://user-images.githubusercontent.com/46253950/172103957-4082a12f-db05-4c32-8658-f76631cab54b.png)
而在修改为 [jekyll-theme-mdui/_includes/comment/comment.html](https://github.com/KeJunMao/jekyll-theme-mdui/blob/2bc7797afa915c4f6cdcd675366169d715b20006/_includes/comment/comment.html) 中的内容后再行配置及安装依赖后问题解决。

----

可能是修改没有同步到rubygems,望同步。

**Comment by KeJunMao** [comment]
#66
