### ISSUE TITLE
replace bootcss CDN with something else that is way faster

### ISSUE THREAD

**Issue by shirooo39** [KeJunMao/jekyll-theme-mdui#64]
How could I change the MDUI CDN from [bootcss](cdn.bootcss.com) to something else?
[bootcss](https://cdn.bootcss.com) is extremely slow to access, it would be amazing if there's a faster CDN solution, or a local file link.

If I recall correctly, MDUI does have a JsDelivr package and JsDelivr is really fast.

---

**I certify that I have first consulted** (check all with "x")

- [ x] [Jekyll documentation ](https://jekyllrb.com/)
- [ ] [jekyll-theme-mdui documentation ](http://mdui.kejun.me/#/)
- [ x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [ x] feature request
- [ ] support request

**Comment by KeJunMao** [comment]
you can change here like this:
https://github.com/KeJunMao/jekyll-theme-mdui/pull/1/files

can you open a pr?

**Comment by shirooo39** [comment]
> can you open a pr?

[please review it](https://github.com/KeJunMao/jekyll-theme-mdui/pull/65/commits/2f942c44717bfc001e6f388eb8b0ed075a425690)
