### ISSUE TITLE
update build

### ISSUE THREAD

**Issue by shirooo39** [KeJunMao/jekyll-theme-mdui#66]
Could you please update the build branch with the cdnjs changes?

How could I build the theme and use it locally?
I tried to run ```gem build jekyll-theme-mdui.gemspec``` but it outputs a .gem file that I have no idea how to use.

For example, when building a VuePress site, the output sits in the same folder as the source inside the /dist/ folder.
Does jekyll do the same or the built theme is stored somewhere else?

**Comment by KeJunMao** [comment]
https://rubygems.org/gems/jekyll-theme-mdui/ 0.5.5

**Comment by KeJunMao** [comment]
```bash
git checkout build # use build barch
rm -rf .git # delete .git (opt)
bundle update # update theme to 0.5.5
bundle exec jekyll s # preview~
```

**Comment by shirooo39** [comment]
> ```shell
> git checkout build # use build barch
> rm -rf .git # delete .git (opt)
> bundle update # update theme to 0.5.5
> bundle exec jekyll s # preview~
> ```

thanks! but I've been able to "detach" the theme and put it directly into the site and made some nice changes to it.

![image](https://user-images.githubusercontent.com/38461122/184191427-ad6db8cd-9f26-4340-81b3-9f5b90ec8d18.png)

and this is how it looks like now

![image](https://user-images.githubusercontent.com/38461122/184190987-1eea0dad-574c-4d23-9eb4-f444513c2e36.png)
