### ISSUE TITLE
在GitHub-pages生成站点地图的解决办法

### ISSUE THREAD

**Issue by gledos** [KeJunMao/jekyll-theme-mdui#8]
可以在根目录新建一个`sitemap.xml`，内容为:
```
---
---
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    {% for post in site.posts %}
    <url>
        <loc>{{ site.url }}{{ post.url }}</loc>
    </url>
    {% endfor %}
</urlset>
```
我不知道怎么把这个弄到手册里......所以我就提交到问题里了......

[方法来源](https://dn-coderq.qbox.me/t/jekyll-di-ba-pian-sheng-cheng-zhan-dian-di-tu/134)

**Comment by KeJunMao** [comment]
嗯，多谢，但是既然github-pages支持sitemap插件，就用插件咯

不想用插件也可以的。

这个主题只依赖分页插件，其他都是可选。

**Comment by KeJunMao** [comment]
@gledos 想帮忙修正文档的话，看看docs目录，顺便看看[这个](http://mdui.kejun.space/#/zh-cn/how-contribution?id=%e6%96%87%e6%a1%a3)，蟹蟹拉~

**Comment by gledos** [comment]
因为我只有一台chromebook......

没法使用git......
