### ISSUE TITLE
关于音乐播放的小问题

### ISSUE THREAD

**Issue by LamGC** [KeJunMao/jekyll-theme-mdui#9]
**I certify that I have first consulted** (check all with "x")

- [ ] [Jekyll documentation ](https://jekyllrb.com/)
- [x] [jekyll-theme-mdui documentation ](http://mdui.kejun.space/#/)
- [x] [jekyll-theme-mdui issues ](https://github.com/KeJunMao/jekyll-theme-mdui/issues)

----

**I'm submitting a**  (check one with "x")

- [ ] bug report 
- [x] feature request
- [ ] support request

----
直接用中文写issue吧。
发现cplayer似乎可以设置播放列表，但主题并没有这个设置(单歌曲)
能在meng.yml的music_player里，把music设为数组来设置播放列表吗？或是怎么写才能做播放列表？
麻烦了qwq

**Comment by KeJunMao** [comment]
因为 `cplayer` 现在由 @EYHN dalao 在开发，这不是重点，重点是更新太频繁了。而且，没记错主题现在的 `cplayer` 已经炸了。

蟹蟹你的建议，一定会搞的。

编辑：刚刚问了下， `cplayer`  短期内还有一次更新。静候吧。

**Comment by LamGC** [comment]
好的，非常感谢(´,,•∀•,,`)

**Comment by KeJunMao** [comment]
@LamGC 加拉~

**Comment by LamGC** [comment]
感谢，幸苦了♪(^∇^*)

**Comment by LamGC** [comment]
@KeJunMao 音乐播放器在使用多音乐播放的时候，会出现【Uncaught TypeError: cplayer is not a constructor】错误，以及歌曲信息读取不了(playlist: [{ src: '', poster: '', name: '', artist: '', }, ]) 然后播放器就不会出现了_(´ཀ`」 ∠)__，你测试的时候是正常的吗？(~￣△￣)~

**Comment by LamGC** [comment]
以及改回单列表也无法播放的奇怪问题，再补一个At @metaphors 麻烦了QAQ
